version: '3.8'

services:
  mindmap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindmap-container
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mindmap.rule=Host(`mindmap.localhost`)"
      - "traefik.http.services.mindmap.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mindmap-network

networks:
  mindmap-network:
    driver: bridge

# Optional: Add volume for persistent data if needed in the future
# volumes:
#   mindmap-data:
#     driver: local
